//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public int idDepartamento { get; set; }
        public string nombre { get; set; }
        public Nullable<int> ubicacion { get; set; }
        public Nullable<int> centroCosto { get; set; }
    }
}
