//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmvc5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vempleados
    {
        [Display(Name = "Codigo")]
        public int id { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        [Display(Name = "Departamento")]
        public string departamento { get; set; }
        [Display(Name = "Fecha de ingreso")]
        public Nullable<System.DateTime> fechaIngreso { get; set; }
    }
}
